spring:
  #  docker:
  #    compose:
  #      enabled: true
  #      file: compose-dev.yml
  #      start:
  #        command: up
  #      stop:
  #        command: down
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:backend}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:backend}
    username: ${DB_USERNAME:backend}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migrations/{vendor}/
    enabled: true
  cloud:
    aws:
      credentials:
        access-key: "${AWS_ACCESS_KEY:accesskey}"
        secret-key: "${AWS_SECRET_KEY:secretkey}"
      region:
        static: "${AWS_REGION:us-east-2}"
      sqs:
        endpoint: "${AWS_SQS_ENDPOINT:endpoint}"

app:
  docs-api-url: "${DOCS_API_URL:(no value)}"
  aws:
    access-key: "${AWS_ACCESS_KEY:no_access_key}"
    secret-key: "${AWS_SECRET_KEY:no_secret_key}"
    session-token: "${AWS_SESSION_TOKEN:}"
    dynamodb:
      endpoint: "${AWS_DYNAMODB_ENDPOINT:dynamodb.us-east-1.amazonaws.com}"

server:
  port: 8082
  servlet:
    context-path: "/clockin"
