# Global config
spring:
  docker:
    compose:
      # We don't want to use docker compose in prod and test
      enabled: false
  profiles:
    # Value comes from Maven profile (pom.xml)
    active: 'prod'
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:backend}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:backend}
    username: ${DB_USERNAME:backend}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    locations: classpath:db/migrations/{vendor}/
    enabled: true
  cloud:
    aws:
      credentials:
        access-key: "${AWS_ACCESS_KEY}"
        secret-key: "${AWS_SECRET_KEY}"
      region:
        static: "${AWS_REGION:us-east-1}"
      sqs:
        endpoint: "${AWS_SQS_ENDPOINT}"

springdoc:
  swagger-ui:
    path: /
    tags-sorter: alpha
  show-actuator: true
management:
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-components: always
    shutdown:
      enabled: true # For debugging
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown

server:
  servlet:
    context-path: "/clock-in"
  port: 8004

jwt:
  token:
    key:
      public: "${JWT_PUBLIC_KEY}"

# --- Custom keys ---

info:
  name: 'Service ClockIn'
  description: 'FIAP SOAT1 2023 - Group 63 - Hackaton - Clock In microservice'
  version: '0.1.2'

app:
  mail:
    host: "${MAIL_HOST}"
    port: "${MAIL_PORT}"
    username: "${MAIL_USERNAME}"
    password: "${MAIL_PASSWORD}"
  docs-api-url: "${DOCS_API_URL:(no value)}"
  aws:
    access-key: "${AWS_ACCESS_KEY:no_access_key}"
    secret-key: "${AWS_SECRET_KEY:no_secret_key}"
    session-token: "${AWS_SESSION_TOKEN:}"
    dynamodb:
      endpoint: "${AWS_DYNAMODB_ENDPOINT:dynamodb.us-east-1.amazonaws.com}"
